TIME_KEYWORDS = {
    "s": "s",
    "se": "s",
    "sec": "s",
    "second": "s",
    "seconds": "s",
    "m": "m",
    "mi": "m",
    "mii": "m",
    "min": "m",
    "mins": "m",
    "mon": "m",
    "mnutes": "m",
    "kinutes": "m",
    "ninutes": "m",
    "minute": "m",
    "minutes": "m",
    "h": "h",
    "hr": "h",
    "hrs": "h",
    "hour": "h",
    "hours": "h",
    "day": "d",
    "days": "d",
    "week": "w",
    "month": "mo",
    "months": "mo",
    "yrs": "y",
    "year": "y",
}

TIME_VALUES = {
    "s": 1,
    "m": 60,
    "h": 60 * 60,
    "d": 24 * 60 * 60,
    "w": 7 * 24 * 60 * 60,
    "mo": 30 * 24 * 60 * 60,
    "y": 365 * 24 * 60 * 60,
}